# Generated by Django 4.2.5 on 2023-09-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('HR', 'HR'), ('MIS', 'MIS'), ('WE', 'WE'), ('CITYMANAGER', 'CITYMANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('FWP', 'FWP')], default='FWP', max_length=100),
        ),
    ]
