# Generated by Django 4.2.5 on 2023-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
