# Generated by Django 4.2.5 on 2023-09-20 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('field_type', models.CharField(blank=True, choices=[('Text', 'Text'), ('Dropdown', 'Dropdown'), ('Radio', 'Radio'), ('Checkbox', 'Checkbox'), ('File', 'File'), ('Number', 'Number')], max_length=100, null=True)),
                ('options', models.CharField(blank=True, max_length=100, null=True)),
                ('num_images', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('req', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('role', models.CharField(choices=[('HR', 'HR'), ('MIS', 'Inactive')], default='Active', max_length=100)),
                ('lock', models.CharField(choices=[('Lock', 'Lock'), ('UnLock', 'UnLock')], default='UnLock', max_length=10)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('cityReg', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hpcl.citymodel')),
            ],
        ),
        migrations.CreateModel(
            name='OutletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('long', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('cityReg', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hpcl.citymodel')),
            ],
        ),
        migrations.CreateModel(
            name='OutletAssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_start', models.DateTimeField(default=datetime.datetime(2023, 9, 20, 23, 56, 13, 425995))),
                ('assignment_end', models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 21, 23, 56, 13, 425995))),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpcl.outletmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hpcl.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField()),
                ('checkin_image', models.ImageField(blank=True, default='', null=True, upload_to='checkin/')),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('checkout_image', models.ImageField(blank=True, default='', null=True, upload_to='checkout/')),
                ('lat', models.CharField(blank=True, default=0.0, max_length=100, null=True)),
                ('long', models.CharField(blank=True, default=0.0, max_length=100, null=True)),
                ('lat1', models.CharField(blank=True, default=0.0, max_length=100, null=True)),
                ('long2', models.CharField(blank=True, default=0.0, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpcl.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('long', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hpcl.outletmodel')),
            ],
        ),
    ]
