# Generated by Django 4.2.5 on 2023-09-20 19:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hpcl', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outletassignmentmodel',
            name='assignment_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 22, 0, 46, 40, 982397)),
        ),
        migrations.AlterField(
            model_name='outletassignmentmodel',
            name='assignment_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 0, 46, 40, 982397)),
        ),
        migrations.AlterField(
            model_name='outletassignmentmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
